### ISSUE TITLE
Status of Roadkill v3 in March 2020 

### ISSUE THREAD

**Issue by dcbrewster** [roadkillwiki/roadkill#104]
I am looking to deploy a new wiki and just wondering about the v3 update.

**Comment by yetanotherchris** [comment]
Now that we know SPA is dead, Roadkill 3 is on its way - the React side is currently being worked on the rather complicated JWT and refresh token part- https://github.com/roadkillwiki/roadkill_new

I would stick with v2 for now, using one of the Cloud images described in the readme.
