### ISSUE TITLE
Deploy RoadKill on Google Cloud. livenessProbe enabled?

### ISSUE THREAD

**Issue by brocoly27** [roadkillwiki/roadkill#112]
Hello!!, 
My company has been using this app for a long time, now I was instructed to migrate to the cloud (Google Cloud).
I was able to dockerize it and deploy it on GKE (Google Kubernetes Engine) however when I set up the Ingress, it requires me to properly declare the livenessProbe and readinessProbe.
Since the application is running fresh. when I do 'http:localhost:80/, automatically redirects me to /install endpoint.

What URL can I use to pass the liveness and readiness proof?
Thanks

**Comment by yetanotherchris** [comment]
I'm impressed you got a Windows container working on GKE!

Could you use /favicon.ico for the liveness? There isn't any health check feature as it's a pre-container or health check application.

**Comment by brocoly27** [comment]
Sure, thank you for your advice, I'll use that then. Thank you so much ;)
