### ISSUE TITLE
SQL Injection attacks

### ISSUE THREAD

**Issue by Siman007** [roadkillwiki/roadkill#125]
Hi has anyone looked at SQL Injection attacks against v2 of roadkill?
From my (very) short time playing with a default MSSQL install (latest v2), it seemed to me to offer little protection. If that's right I guess it's not suitable for exposure on the Internet.

Thanks
s

**Comment by yetanotherchris** [comment]
Roadkill v2 uses Dapper and Lightspeed ORM for SQL (Server, mySQL), for its installation and CRUD repositories

Perhaps you would like to raise a ticket with Mindscape or https://github.com/DapperLib/Dapper :)
