### ISSUE TITLE
new release planned? 

### ISSUE THREAD

**Issue by 304NotModified** [roadkillwiki/roadkill#13]
Is there a new release planned? 

We really like the [page-attachments](http://roadkillwiki.userecho.com/topic/354042-page-attachments/) idea!

**Comment by gandarez** [comment]
@304NotModified the ability to attach images is already there.

**Comment by yetanotherchris** [comment]
I'm going to write a news group post about this - I'm waiting for vNext before I do anything major to the project, as I want it vNext ready first then I can add new features. There's a lot of changes in v5 to Razor, IoC and the project structure, plus support for Creole and Mediawiki will be removed in the next version.

As a wild guess, I'd say September will be when things start happening in Roadkill again

**Comment by 304NotModified** [comment]
@gandarez as described in the userecho link?

**Comment by 304NotModified** [comment]
Thanks for the response @yetanotherchris.  

One question, v5 Of what? Roadkill? Mvc?

**Comment by 304NotModified** [comment]
And will it be github flavoured Markdown?

**Comment by gandarez** [comment]
@304NotModified yes. In the editor you can attach images to your post.

![image](https://cloud.githubusercontent.com/assets/782854/7659284/43b972b0-fb17-11e4-9a8a-9a061d6be582.png)

**Comment by 304NotModified** [comment]
Cool! So userecho is out to date?

**Comment by yetanotherchris** [comment]
The new technologies will be ASP.NET v5, MVC 6, StructureMap 3, CommonMark.NET

**Comment by yetanotherchris** [comment]
@gandarez I think @304NotModified means in Roadkill not in Github. The UserEcho list needs some love, the first few feature I want to add are a better file manager (similar to the Wordpress one) which will then allow file attachments for pages to be a lot easier, and after that a decent link dialog for the editor.

Moving to one markup type is going to make the editor a lot better, I've also got plans for that too - maybe using a 3rd party Markdown editor that does the previews itself.

**Comment by 304NotModified** [comment]
I'm talking of course about roadkill and not GitHub. ...

**Comment by gandarez** [comment]
I attached a screenshot from roadkill running in my company. I'm not even talking about github also.

**Comment by yetanotherchris** [comment]
Announcement/roadmap on its way soon, I'm closing this as it's not a bug

**Comment by 304NotModified** [comment]
:+1:
