### ISSUE TITLE
Assets don't work on fresh install

### ISSUE THREAD

**Issue by morrislaptop** [roadkillwiki/roadkill#16]
Hi,

Trying to get this working on a default install however all the assets files are broken. All the assets do a 302 direct to the login screen.

![aws](https://cloud.githubusercontent.com/assets/67807/8042265/0321358c-0e16-11e5-8b8e-1a069e9d4255.png)

Cheers,
Craig

**Comment by yetanotherchris** [comment]
Without seeing your IIS settings it's a bit hard to figure out, but it's
performing a redirect which implies IIS has some kind of handler not set or
module missing. You could try putting an image in the root folder and
seeing if that gets served up.

**Comment by morrislaptop** [comment]
Thanks for responding - ended up being permissions issue when running as an application!
