### ISSUE TITLE
Proposal: add code coverage

### ISSUE THREAD

**Issue by 304NotModified** [roadkillwiki/roadkill#31]
I'm curious what the code coverage is of the unit tests.

We have very good experience with codecov.io in combination with AppVeyor :)

So proposal: add codecov.io integration in AppVeyor.

Steps:

1. Create account in codecov.io (free, no token needed)
2. Edit appveyor.yml

Add: 

```
clone_folder: C:\projects\roadkill
```
and add `after_test:` (change xunit to nunit and change the `-filter`

Example of NLog, [see GitHub](https://github.com/NLog/NLog.windows.forms/blob/master/appveyor.yml)
```
after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"c:\projects\nlogweb\NLog.Windows.Forms.Tests\bin\Release\NLog.Windows.Forms.Tests.dll\" -appveyor -noshadow"  -returntargetcode -filter:"+[NLog.Windows.Forms]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"

```

**Comment by ctrl-alt-d** [comment]
:+1:

**Comment by yetanotherchris** [comment]
It was 80% with dotcover, which needed a lot of things filtering out

http://www.anotherchris.net/wp-content/uploads/2013/12/coverage.png

I'll get this setup

**Comment by 304NotModified** [comment]
yes, you can replace `"%xunit20%\xunit.console.x86.exe"` with `nunit-console` I think

**Comment by yetanotherchris** [comment]
I used Coverall as Appveyor already has docs for it, but it uses OpenCover under the hood. OpenCover is decent for a free app, so thanks for the suggestion.

**Comment by 304NotModified** [comment]
Coveralls is also fine :) 

Nice that the badge is added!
