### ISSUE TITLE
Creole to Markdown tool

### ISSUE THREAD

**Issue by 304NotModified** [roadkillwiki/roadkill#38]
> Version 3 will support Markdown, using the CommonMark standard.
> ..
> There's plans to create a tool to do some primitive conversion of Creole to Markdown to help people upgrade.

Can you tell me some more about these plans? Any idea to use a existing tool (if there is some)? Will this  a separate tool? Can we do the conversion already in Roadkill 2?

**Comment by 304NotModified** [comment]
Some gists, which could be helpful:

- https://gist.github.com/snopoke/39a062b334473b18ddb0
- https://gist.github.com/mxswd/3158772

**Comment by yetanotherchris** [comment]
Thanks I'll probably take those regex tools and add a `CreoleToMarkdownConverter` that can live under the admin tools section
