### ISSUE TITLE
Master branch doesn't work right. Files are not included from project

### ISSUE THREAD

**Issue by thenrich2009** [roadkillwiki/roadkill#52]
What's up with the master branch? The latest changes is making the app not work right, I noticed jquery is not being load because the bundle.c is not part of the project anymore. The I find out RoadkillApplication.cs is also not part of the project anymore. Where is the stable branch?

**Comment by yetanotherchris** [comment]
What isn't working - is it runtime or compile time? The CI is working so I would guess you mean runtime.

For now master is the unstable branch, which will change in the next version (3). For the latest stable version try the v2 tag:

https://github.com/roadkillwiki/roadkill/tree/v2.0

**Comment by thenrich2009** [comment]
There are javescript errors. One because roadkill.min.js is missing. It doesn't exist at all. Then it says $ is not defined. That's because jquery is not loaded. I verified there's no script tag to load.. and it's for the reasons I mentioned in the post. bundle.cs is not part of the project and therefore it doesn't run.

If I type in the textbox in a new page, there's no preview happening. Also when I run in the debugger, some Dispose() methods are giving exceptions about object already disposed in the SaveChanges() method. This is all from just spending an hour on it trying to figure why I am getting all these issues and so I think there are many other issues. Are you checking in code that you are still working on?

I am going back to the latest stable version I have from a few months ago.
