### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by nilmitra** [roadkillwiki/roadkill#54]
I am facing several errors while setting the solution. I believe I am missing out on something. Will appreciate help. 
**Problems Facing:**
1. All "=>" giving error. 
2. string sql = $"delete from {TableName} where id=@Id";.  - "$" Giving Error if I change it to "@" it works. 

Please help.

**Comment by svgorbunov** [comment]
README.md:

## For Developers

### Pre-requisites

To setup Roadkill on a developer machine, you will need:

* Visual Studio 2015

**Comment by nilmitra** [comment]
Thanks.. My bad..

**Comment by yetanotherchris** [comment]
Yes that looks like you need C# 6 (VS2015)
