### ISSUE TITLE
Azure demo not working

### ISSUE THREAD

**Issue by carlcrawford** [roadkillwiki/roadkill#55]
I get the following error when trying to run the demo on the front page:

Server Error in '/' Application.

Runtime Error 
  Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated.

**Comment by yetanotherchris** [comment]
Thanks for reporting this, the MSDN subscription that the Azure site was using had run out.

It's now up again: http://demo.roadkillwiki.net

**Comment by matfricker** [comment]
Unable to navigate to the demo site. I have tried multiple times today. I am not receiving the "Runtime error" above mentioned above. Site just seems to be timing out my side.

**Comment by yetanotherchris** [comment]
The url is now http://roadkilldemo.azurewebsites.net/ @matfricker I've updated the homepage too

**Comment by matfricker** [comment]
Thanks @yetanotherchris. Think the readme.md link needs updating. :)

**Comment by yetanotherchris** [comment]
Thanks, I've updated the readme too
