### ISSUE TITLE
Typescript - Left-hand side of assignment expression cannot be a constant or a read-only property

### ISSUE THREAD

**Issue by PullmanHacker** [roadkillwiki/roadkill#61]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Left-hand side of assignment expression cannot be a constant or a read-only property.	Roadkill.Web	C:\Users\jeffm\Downloads\roadkill-2.0\roadkill-2.0\src\Roadkill.Web\Assets\Scripts\roadkill\filemanager\ajaxrequest.ts	58	

		private makeAjaxRequest(url: string, data: any, errorMessage: string, successFunction: (data: any) => void)
		{
			var request = $.ajax({
				type: "POST",
				url: url,
				data: data,
				dataType: "json"
			});

			request.done(successFunction);
			
			request.fail(function (jqXHR, textStatus, errorThrown : SyntaxError)
			{
				// Logged out since the call was made
				if (errorThrown.message.indexOf("unexpected character") !== -1)
				{
					window.location = window.location;  "ERROR LOCATION"
				}
				else
				{
					toastr.error(errorMessage + errorThrown);
				}
			});
		}

**Comment by yetanotherchris** [comment]
This is an issue with Typescript 2 (Roadkill version 2 uses 1.x)

**Comment by yetanotherchris** [comment]
This is fixed in the `version-2` branch we varies very slightly from the release now, to fix this issue for Azure CI deploys.
