### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by flyingOTR** [roadkillwiki/roadkill#62]
Having issues with getting this thing up and running.  I keep getting an "LDAP string is empty"... I've searched the entire solution and do not see where this is pulling from.  

The setup page does not work.  Any clarification on initial setup would be greatly appreciated.

**Comment by yetanotherchris** [comment]
Are you installing with Active Directory for security?

**Comment by flyingOTR** [comment]
Yes.

Sent from my iPhone

On Apr 5, 2017, at 11:57 AM, Chris S. <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you installing with Active Directory for security?

**Comment by yetanotherchris** [comment]
Can you check each field you've filled in - it may be worth starting the installation again from scratch by closing the browser.

**Comment by flyingOTR** [comment]
It wont load the installation pages… it errors out with the empty ldap string.

**Comment by yetanotherchris** [comment]
You'll need to clear the installed flag on the roadkill.config file

**Comment by flyingOTR** [comment]
It is… I’m wondering if im missing some files???

**Comment by flyingOTR** [comment]
Are there clearer instructions on the setup?  I’m a web dev guy and this is very confusing to me.

**Comment by yetanotherchris** [comment]
It should be false

**Comment by flyingOTR** [comment]
Yes I'm aware of that. It is set to false.


Sent from my iPhone

On Apr 5, 2017, at 2:49 PM, Chris S. <notifications@github.com<mailto:notifications@github.com>> wrote:

It should be false

**Comment by yetanotherchris** [comment]
That is strange. Perhaps try deleting the config file (backing it up first)
and see if the app shows a different error

**Comment by flyingOTR** [comment]
[SecurityException: The LDAP connection string is empty]
   Roadkill.Core.Security.Windows.ActiveDirectoryUserService..ctor(ApplicationSettings settings, IRepository repository, IActiveDirectoryProvider service) in d:\projects\roadkill\src\Roadkill.Core\Security\Windows\ActiveDirectoryUserService.cs:56

I’m not sure where it is pulling this from – this application is not on ANY “D” drive.

**Comment by yetanotherchris** [comment]
D: is just the drive that the original source code was compiled on, that's the stacktrace using the debugging symbols (Roadkill was compiled on a D: drive)

**Comment by flyingOTR** [comment]
I have not been able to get roadkill working and have switched to ScrewTurn WIKI.  The setup was simple and well documented.
