### ISSUE TITLE
Translation to Hebrew

### ISSUE THREAD

**Issue by saguiitay** [roadkillwiki/roadkill#64]
I'd like to contribute a translation to Hebrew.
Do I still need access to POEditor.com, or can I just send a PR?

**Comment by yetanotherchris** [comment]
SIgn up on POEditor please

**Comment by yetanotherchris** [comment]
You'll need to select Hebrew in POEditor

**Comment by saguiitay** [comment]
Hebrew is not in the list of languages

**Comment by yetanotherchris** [comment]
Give it a try now

**Comment by saguiitay** [comment]
Joined for the Site... Installer still doesn't have Hebrew as an option

**Comment by yetanotherchris** [comment]
Sorry I thought it was global, it should be there now.

**Comment by saguiitay** [comment]
Joined. Thanks.
