### ISSUE TITLE
SQL Server 2014 Support in Version 3.0?

### ISSUE THREAD

**Issue by Yohlo** [roadkillwiki/roadkill#67]
I noticed in the archived google group you mentioned a new update rolling out by the end of this year. Any update on that? and, would it support SQL Server 2014?

**Comment by yetanotherchris** [comment]
Hi Yohlo, yes a conversion to .NET Core is happening right now which is version 3:

https://github.com/roadkillwiki/roadkill/commits/dotnet-core

It a major upgrade but will bring Linux and container support with it allowing for much faster update cycles.

For SQL Server: it should support 2012, 2014, 2016 and beyond, Roadkill doesn't make use of any SQL Server specific features
