### ISSUE TITLE
Readme.MD issue and link on roadkillwiki.net issue

### ISSUE THREAD

**Issue by xantari** [roadkillwiki/roadkill#70]
Readme.MD on github has error. Try demo link has this:
http://roadkill-demo.azurewebsites.net

But that link crashes / is not running.

http://www.roadkillwiki.net has link to DOWNLOAD, but it is going to codeplex which is ceasing operation, it should be pointed to github instead?

**Comment by yetanotherchris** [comment]
Fixed and fixed, thanks for reporting it
