### ISSUE TITLE
MediaWiki table support

### ISSUE THREAD

**Issue by poostwoud** [roadkillwiki/roadkill#72]
Hi,

I'm trying to create a table using the MediaWiki markup, however it doesn't seem to work. I'm following the examples on https://www.mediawiki.org/wiki/Help:Tables. For the first example:

{|
|Orange
|Apple
|-
|Bread
|Pie
|-
|Butter
|Ice cream 
|}

The output shows only:

{|

Are tables not yet supported or did I miss something in the docs?

Cheers,

Peter

**Comment by yetanotherchris** [comment]
The tables are meant to work, but the parser is a rather useless 3rd party Microsoft implementation. The next version of Roadkill will be Markdown only using Markdown extensions, so unfortunately this won't be fixed if it's not working quite right.
