### ISSUE TITLE
Steps to integrate Roadkill with mvc application which uses identity server 3 authentication

### ISSUE THREAD

**Issue by amrutasonawane** [roadkillwiki/roadkill#73]
I have my web application uses MVC 5 and identity server3 authentication.I want to use roadkill .net wiki application which uses parent project authentication.Could anyone explain to me what are the steps for it from scratch? I have added roadkill NuGet package in my project but it is given an error.so how to install it my MVC project and how to add parent project authentication in roadkill. I am using vs2015 community edition.
-- | --

**Comment by yetanotherchris** [comment]
I've answered this now on Stackoverflow: https://stackoverflow.com/q/45631908/21574
