### ISSUE TITLE
install - how to in wiki very unclear

### ISSUE THREAD

**Issue by figuerres** [roadkillwiki/roadkill#74]
i saw "Once your site is created and the file is unzipped, copy/FTP the unzipped Roadkill files to your website root folder."

?  copy which files ?  the zip that i get from github has multiple folders of source files and some of the files look to be for making dlls that go into the web site.
seems like on;ly the web project files should be used but even then that is not a working build i think...

**Comment by yetanotherchris** [comment]
The ZIP file you need is from the releases: 

> https://github.com/roadkillwiki/roadkill/releases/tag/v2.0

You unzip that and copy all of it to your website root.

**Comment by figuerres** [comment]
thanks i did figure it out later that day, we are testing the code and seeing if this is what we want to use.
