### ISSUE TITLE
DataImport from SharepointWiki

### ISSUE THREAD

**Issue by hrishikeshtt** [roadkillwiki/roadkill#75]
We are planing to migrate existing sharepoint wiki data to Roadkill wiki. Is there any way to do that ?

**Comment by yetanotherchris** [comment]
You will have to do this by manually creating an importer. The schema is really simple in roadkill - just a `pages` table, and a `page_content`. It's not out of the box I'm afraid, and you may have problems with converting your Sharepoint markup to Markdown (or Creole but I'd advice sticking to Markdown).
