### ISSUE TITLE
Make Compatible with Azure's Cosmos Document DB Emulator

### ISSUE THREAD

**Issue by n-ate** [roadkillwiki/roadkill#78]
This should be a super easy fix. Azure's Cosmos Database supports MongoDB queries. The emulator however only supports a single connection string:

`mongodb://localhost:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==@localhost:10255/admin?ssl=true&3t.sslSelfSignedCerts=true`

The documentation and download link for the emulator can be found here, the download is a one click install with no configuration: [https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator](emulator)

Currently roadkill chokes on the connection string, specifically: 

> 3t.sslSelfSignedCerts=true

**Comment by n-ate** [comment]
On second thought this isn't an easy fix it is part of the mongodb driver.

**Comment by yetanotherchris** [comment]
I have experimented with DocumentDB and the MongoDB driver wasn't full compatible with it, I think the problem was DocumentDB to implement all of the interface
