### ISSUE TITLE
LightSpeedPAgeRepository.cs 'cannot access a disposed object'

### ISSUE THREAD

**Issue by atmalone** [roadkillwiki/roadkill#81]
_**Root cause: LightSpeed repository.**_

I am running into an issue after I have successfully established a DB connection and have the site running.
The error occurs on initial load, and whenever a link is clicked to navigate to another page within the project. I am unsure of what the issue with the **Dispose()** method and **unitOfWork** could be. Has anyone experienced the same error setting up their instance?

![image](https://user-images.githubusercontent.com/20585300/32732208-c85dcd54-c883-11e7-8007-bfe24a3acfa3.png)

Regards.

**Comment by yetanotherchris** [comment]
This error can be ignored - is it throwing errors on your Roadkill instance that cause the site to crash?

**Comment by Yannick86** [comment]
How to fix this?

In visual studio I keep getting this error;
System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'UnitOfWork'.'

Triggered from:
using System;
using System.Web;
using StructureMap.Web.Pipeline;

namespace Roadkill.Core.DependencyResolution.StructureMap
{
	public class StructureMapHttpModule : IHttpModule
	{
		public void Dispose()
		{
		}

		public void Init(HttpApplication context)
		{
			context.BeginRequest += (sender, e) => LocatorStartup.Locator.CreateNestedContainer();
			context.EndRequest += (sender, e) =>
			{
				try
				{
					**HttpContextLifecycle.DisposeAndClearAll();**
					LocatorStartup.Locator.DisposeNestedContainer();
				}
				catch (InvalidOperationException)
				{
					// Catch HttpContextLifecycle.DisposeAndClearAll(); issues
				}
			};
		}
	}
}
