### ISSUE TITLE
Markdown H1 tags (single #) not added to {TOC}

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [roadkillwiki/roadkill#83]
When adding `<H1>` tags to a Markdown page (using `#<HeaderName>`), top-level tags are skipped in the TOC block. Instead, `<H2>` tags are rendered as top-level in the TOC.

To reproduce this issue, set Roadkill to use Markdown syntax, then create a page with the following content:
```md
{TOC}

#Foo
##Foo1
###Foo1A
##Foo2
#Bar
##BarAlpha
###Baz
##BarBeta
```

The generated TOC for the above page skips over `Foo`/`Bar`, instead listing `Foo1`, `Foo2`, `BarAlpha`, and `BarBeta` as top-level TOC elements.

**Comment by yetanotherchris** [comment]
h1 are ignored by design, as the page is only meant to have a single H1.

Could you use h2s onwards?
