### ISSUE TITLE
question: Edit and Page Info buttons are blank

### ISSUE THREAD

**Issue by owenlanders** [roadkillwiki/roadkill#84]
![image](https://user-images.githubusercontent.com/2601957/37175365-ee935ae2-22de-11e8-8ffb-755b0361d16f.png)
version is 2.0.275, fresh install last week

This is in all pages in all themes.

**Comment by yetanotherchris** [comment]
Could you press F12 in Chrome, reload the page and see under Network why the images aren't loading?

**Comment by Yannick86** [comment]
In IE they wont load for me either, in Chrome it works perfectly.

**Comment by Yannick86** [comment]
Ok nevermind .. on the server IE 10 was in compatibility view .. hope this fixes it for someone else some day :)

**Comment by yetanotherchris** [comment]
I'll add Edge+ support only for v3. It's a shame IE has to spoil it for everyone 😛
