### ISSUE TITLE
Site Settings - "Test" returns empty json

### ISSUE THREAD

**Issue by marbjorix** [roadkillwiki/roadkill#86]
Love RoadKill! And sorry to disturb: After installing (Roadkill Wiki (2.0.275))  everything works fine, but now (after creating some content and installing the plugin "External links in new window") when I on the **Site Settings** page click the Test button for Database and/or File manager I get a red popup-alert: `Something went wrongSyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`
I have checked the response (Developer tools), and it's empty (therefore the error, I guess). Everything seems fine but this error message worries me. Any idea what the problem can be?

**Comment by yetanotherchris** [comment]
Could you try deleting everything from your roadkill_settings table? That appears to be the issue

**Comment by marbjorix** [comment]
Thanks for the quick feedback. 
Would it then be possible to recreate the content afterwards (I have spent some hours filling in content) - and would it recreate the problem as well? 
BTW could it be my special characters (æøå) in the headlines/titles which is the cause of the problem?

**Comment by marbjorix** [comment]
And what/where is the roadkill_settings table? I have looked in the SQLite-db, but no settings-table there. Is it the Roadkill.config-file? Or?

**Comment by yetanotherchris** [comment]
Are you using SQLite? Do you already have a lot of content in the wiki?

**Comment by marbjorix** [comment]
Just a couple of hours hard work that I would be sorry to lose. I've made a SQL-backup though. And I could possibly backup the entire project as well. 
What seems to be the problem?

**Comment by marbjorix** [comment]
Yes - SQLite :-)

**Comment by yetanotherchris** [comment]
Firstly I would seriously consider using something other than SQLite, as it gets very slow after just a small amount of content. It was a bad choice to include it in Roadkill and will be removed in the next version 😱 

But for the settings problem - can you see the contents of the roadkill_settings table? It should have two rows in it, both with JSON.

**Comment by marbjorix** [comment]
No roadkill_settings table as far as I can see: 
![2018-03-15_214750](https://user-images.githubusercontent.com/37374821/37490448-fd561620-289a-11e8-9b18-82781e5d2dac.jpg)
Could it be this:
![2018-03-15_215323](https://user-images.githubusercontent.com/37374821/37490675-9d784290-289b-11e8-9a41-61b7676302fc.jpg)
