### ISSUE TITLE
The group Admin could not be found

### ISSUE THREAD

**Issue by ballwanek** [roadkillwiki/roadkill#89]
Setting up roadkill and after some small things that were fixed,
i managed to run the web installer. 

I am running on 2012 R2 with IIS 8.5 and SQLserver 2012
connection string works. and the install pages worked.
( i dont know if it is possible to run the install again ? )

(@Html.Action("BootstrapNavMenu", "Home"))

I thought it would be a good idea to use LDAP.

how to fix this ? or where is the LDAP connection located ?

Source File: d:\develop\IIS\wiki\Themes\Responsive\Theme.cshtml    Line: 22 

@Html.Action("BootstrapNavMenu", "Home")

Line 20: 			</div> 
Line 21: 			<div id="bootstrap-nav-menu"> 
Line 22: 				@Html.Action("BootstrapNavMenu", "Home")
Line 23: 			</div> 
Line 24: 			<div id="search" class="searchbar navbar-right hidden-xs hidden-sm">
--

**Comment by yetanotherchris** [comment]
Is this using Active Directory or a standard LDAP directory?

**Comment by ballwanek** [comment]
Hi Chris,

thanks for helping me.

During the install ( web interface of roadkill )

there was the option to use LDAP ( or the users from active directory )

i used this connection string for the LDAP link, like this one.
LDAP://dc1.corp.domain.com/ 
LDAP://domain.local/ ( in my case, i want to use it for a local internal wiki. ) 

if i open this in a browser i get an interface / screen to search, a user.

so i think i have to check where roadkill is saving it settings. 
or mabey not use DLAP/Active directory? 

it is running on a 2012R2 Server with SQL-Server2014
On the database there were 4 new tables created after the installation.

thanks

**Comment by ballwanek** [comment]
Sorry for closing, this form interface is new to me.

**Comment by ballwanek** [comment]
Hi Chris,

I added the Group name "Admin", and added a few users from active directory......

and i get the message.
There is no first page, or main page

**Comment by ballwanek** [comment]
Hi Chris,

i hope you can help me with i think the last part to get it working.
i can make new page's, but after saving i get this error from the web.config.
I quickly googled the error, but i have no idea, what is the problem.


Server Error in '/wiki' Application.
Configuration Error
Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

Parser Error Message: The configSource file 'Roadkill.config' is also used in a parent, this is not allowed. 

Source Error: 


Line 10: 	</configSections>
Line 11: 
Line 12: 	<roadkill configSource="Roadkill.config" />
Line 13: 	<connectionStrings configSource="connectionStrings.config" />
Line 14: 

Source File: D:\develop\IIS\wiki\web.config    Line: 12

**Comment by yetanotherchris** [comment]
What is in your parent? Are you on shared hosting?

**Comment by ballwanek** [comment]
Hi Chris,

From what i read in the documentation, there is written to make an Application (name) in the IIS manager.
And i did that, and part off the application started running, but this upper error came.

The solution is not to name this also 'wiki', i changed wiki to wiki_(company name) and all problems were gone.

What is also nice about this wiki roadkill is the web interface for the installer.

Also we started adding some pages and test a bit, and it looks like all is working.
The LDAP/Active Directory, is real handy.

Also the server is an in company file/exchange server.

Thanks.

**Comment by yetanotherchris** [comment]
Glad you sorted it all out!


Chris
