### ISSUE TITLE
Is it possible to install a new instance of Roadkill without resetting the provided database?

### ISSUE THREAD

**Issue by daniel-cordeiro** [roadkillwiki/roadkill#91]
Hello! First, let me say thank you for this amazing project and all the work done so far!

I have a question. I installed the stable release version of the wiki and I added some users, pages and enabled some plugins. Then, I cloned the project in order to slightly modify the "all pages" view, dividing the pages with different tags into categories and organizing the view with "expand-collapse" headings. I also modified the mediawiki theme slightly.

Now, I wanted to use my original postgres database, which contains the pages and the content, the users and the plugin information. I used the tool provided to export the database as SQL and I can recreate all the tables and its contents.

I published my version of the project (Roadkill.Web) using Visual Studio and I can run my published version locally using IIS Express.

However, any database that I specify on the connection string when installing gets wiped. I tried dropping the database, creating a new one with the same name and populating its tables with my values. When I do that, I get this error:
![bufferedstream error](https://user-images.githubusercontent.com/14896318/44863157-434b6b00-ac74-11e8-8c58-53feee182c92.PNG)

I also tried to install using the unattended url and specifying the connection string through there but it seems to delete the database as well. Changing the connection string manually to a new filled database results in that error too.

So, I would like to know if it is possible to preserve a filled database between installations. If not, is there a way around this? My major concern is having the plugins enabled (primarily the ToC) when filling my database with old pages and page contents using a SQL script. 

Thanks!

**Comment by yetanotherchris** [comment]
Could you try updating the NpgSql package perhaps? Googling that error, this bug might be the culprit:

https://github.com/npgsql/npgsql/issues/252

I don't think it's a Roadkill-related one, at least not directly.

**Comment by daniel-cordeiro** [comment]
I couldn't find NpgSql nor LightSpeed package references on the project and manually updating the dll produced a compilation error because it isn't expecting the newer version. The error indicates that there's a packages.config referencing NpgSql somewhere but I can't find where.

Anyway, changing to Sql Express worked fine.

**Comment by yetanotherchris** [comment]
Glad you fixed the issue, SQL Express is the easiest option, definitely.
