### ISSUE TITLE
Resize local images

### ISSUE THREAD

**Issue by thomastwoodward** [roadkillwiki/roadkill#94]
Is there a way to resize local images on a page? For example something like 

`![Image1](/MyImage.PNG){width=30}`

I have tried with embedded html, following the steps described in the [Google group post](https://groups.google.com/forum/#!topic/roadkillwiki/Ye_C5yYf99Q)

`<img src="/roadkill/App_Data/Attachments/MyImage.PNG" width="30">`

but it doesn't find the image on the local machine. I also tried stripping out the first part of the path (just like it does if I choose an image from the selector), but still no luck.

`<img src="/MyImage.PNG" height="30">`

Strangely, it works fine if the source is from the web

`<img src="https://github.com/favicon.ico" width="30">`

**Comment by yetanotherchris** [comment]
What is your attachments path in your configuration? That's the path you use in your `img` tag

**Comment by thomastwoodward** [comment]
My attachments folder is configured as "\~/App_Data/Attachments", but the image does not come in when I use "~/App_Data/Attachments/MyImage.PNG" or "/App_Data/Attachments/MyImage.PNG" in the `img` tag.

**Comment by yetanotherchris** [comment]
You don't need the app_data part, just /attachments

**Comment by thomastwoodward** [comment]
No luck with that either: `<img src="/Attachments/MyImage.PNG" width="30">`

**Comment by yetanotherchris** [comment]
Can you upload files?

**Comment by thomastwoodward** [comment]
I can upload files and I can imbed images with markdown. This works fine, for example

`![Image1](/MyImage.PNG)`

**Comment by yetanotherchris** [comment]
What is the `src`  attribute for the image tags those produce?

**Comment by thomastwoodward** [comment]
Great question. The generated HTML is 

`<img src="/roadkill/Attachments/MyImage.PNG">`

I can put that directly into my wiki page and it allows me to resize. Thanks so much for your help!
