### ISSUE TITLE
Deployment on Azure

### ISSUE THREAD

**Issue by jolivem** [roadkillwiki/roadkill#95]
Hi,
I am trying to deploy Roadkillwiki on Azure, and it fails with the connection string to the DB. 
I can see in the RoadkillWiki github home page a paragraph about Quick start, but the link to "Azure Instructions" is broken.
Would you have the target of the link ?
Thanks
Michel

**Comment by yetanotherchris** [comment]
The docs now live under the docs folder, the Azure instructions are here:

https://github.com/roadkillwiki/roadkill/blob/master/docs/azure.md
