### ISSUE TITLE
Not working on IIS

### ISSUE THREAD

**Issue by Yannick86** [roadkillwiki/roadkill#96]
Hey all,

I've followed the installation guide and set everything up on IIS, but when I navigate to the page I always get the following. I've tried to setup the installation myself ( by running the SQL script & filling in the connectionstring config ) but this also does not work. Is there something wrong with the code?

Regards,
Yannick

Compilation Error 
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: CS0305: Using the generic type 'Roadkill.Core.Mvc.WebViewPages.RoadkillViewPage<T>' requires 1 type arguments

Source Error:

 

Line 40:     
Line 41:     
Line 42:     public class _Page_Views_Home_Index_cshtml : Roadkill.Core.Mvc.WebViewPages.RoadkillViewPage {
Line 43:         
Line 44: #line hidden 

Source File: c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\wiki\425c0f36\caa797b6\App_Web_index.cshtml.a8d08dba.5bsrlw3_.0.cs    Line: 42

**Comment by Yannick86** [comment]
By the way, in web.config I had to comment all lines regarding razor ... because I kept getting the following error:

HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.Detailed Error Information:
Module    IIS Web Core 
Notification    BeginRequest 
Handler    Not yet determined 
Error Code    0x800700b7 
Config Error    There is a duplicate 'system.web.webPages.razor/pages' section defined  
Config File    \\?\C:\Projects\Production WebApplications\Wiki\web.config 
Requested URL    http://localhost:80/Wiki 
Physical Path    C:\Projects\Production WebApplications\Wiki 
Logon Method    Not yet determined 
Logon User    Not yet determined 
 Config Source:
    7: 			<section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
    8: 			<section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
    9: 		</sectionGroup>

**Comment by yetanotherchris** [comment]
This sounds like the app pool is the wrong .net version from that second error message

**Comment by Yannick86** [comment]
The app pool is running on v4.0.30319, this seems correct to me?

**Comment by yetanotherchris** [comment]
Is this on your own personal laptop/desktop or a server? That error can happen from Visual Studios not upgrading properly, or 3.5 and 4.0 issues if I remember rightly, but it's been a few years since I've had to struggle with it.

**Comment by Yannick86** [comment]
It's on a win 2012 server

**Comment by Yannick86** [comment]
Can you copy paste your web.config? 
I think there's something wrong with the provided file.

**Comment by yetanotherchris** [comment]
The one you should be using is from

https://github.com/roadkillwiki/roadkill/releases

Don't clone master, that probably won't work

**Comment by Yannick86** [comment]
Yep same as I'm using .. god damnit :(

**Comment by Yannick86** [comment]
O boy .. problem was that it was an application in the existing Default web site ... I've created a blank website & not it works ..

New problem though; in the installation clicking 'Test' to check if it has access to web.config it wont do anything? I've unchecked the read-only flag on the file & the entire folder.

**Comment by Yannick86** [comment]
What is the admin password that is hashed in the sql script?

**Comment by yetanotherchris** [comment]
Closing this as it looks like it's resolved. There's no passwords stored in the repo by the way, those are just test fixture passwords
