### ISSUE TITLE
Code tags?

### ISSUE THREAD

**Issue by Yannick86** [roadkillwiki/roadkill#97]
Is there a way to add for example C# code and show it as code?
Like you have the 'Insert Code' button in this text field here on github?

**Comment by yetanotherchris** [comment]
There's a syntax highlighter plugin which you need to enable. You then use the tag (for creole)

`[[[code lang=sql|ENTER YOUR CODE HERE]]]`

**Comment by yetanotherchris** [comment]
It uses this: http://alexgorbatchev.com/SyntaxHighlighter/

**Comment by Yannick86** [comment]
Awesome, thanks dude :)
